<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-BeFit-05abbdb7-55ae-4d76-8ad7-5c95f61abd2b</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Models\NewFolder1\**" />
    <Compile Remove="Models\NewFolder2\**" />
    <Compile Remove="Models\NewFolder\**" />
    <Content Remove="Models\NewFolder1\**" />
    <Content Remove="Models\NewFolder2\**" />
    <Content Remove="Models\NewFolder\**" />
    <EmbeddedResource Remove="Models\NewFolder1\**" />
    <EmbeddedResource Remove="Models\NewFolder2\**" />
    <EmbeddedResource Remove="Models\NewFolder\**" />
    <None Remove="Models\NewFolder1\**" />
    <None Remove="Models\NewFolder2\**" />
    <None Remove="Models\NewFolder\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="8.0.21" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.21" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.21" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.7" />
  </ItemGroup>

</Project>
